### ISSUE TITLE
Importing Icon Doesn’t Return Path Anymore

### ISSUE THREAD

**Issue by nathanaelphilip** [vuejs-templates/webpack#1031]
```
"vue": "^2.5.2",
"vue-router": "^3.0.1",
"url-loader": "^0.5.7",
"vue-loader": "^13.3.0",
"vue-style-loader": "^3.0.3",
"vue-template-compiler": "^2.5.2",
```
At some, importing an SVG icon like this: `import IconEdit from '@/assets/icons/edit.svg'` would return the path. But now, when I try to access it, it’s an object `[Object object]` – is there a way to get the path from this object?

using `require('@/assets/icons/edit.svg')` returns the same object

https://www.dropbox.com/s/h6yuqmuvvg7p1kh/Screenshot%202017-11-07%2015.09.05.png?dl=0

Tried following #126, but that doesn’t seem to help :)

**Comment by LinusBorg** [comment]
I'm sorry, I would need some runnable code to say anything about this.

Because I'm running a fresh install of the template right now, and changed the import of the default Vue logo into a require, and it works nicely:
![bildschirmfoto 2017-11-08 um 21 16 02](https://user-images.githubusercontent.com/1444526/32572135-fe7e1c94-c4c9-11e7-9313-1c36f8536537.png)

![bildschirmfoto 2017-11-08 um 21 16 29](https://user-images.githubusercontent.com/1444526/32572157-0e0e9698-c4ca-11e7-8251-b6573e40e10a.png)

**Comment by nathanaelphilip** [comment]
hi @LinusBorg can you try a `.svg` instead of a `.png`

**Comment by LinusBorg** [comment]
I can, just have to find one :D

I doubt that the result will be different because both imports are done with the same loader config.

**Comment by LinusBorg** [comment]
Tested, works just fine.

**Comment by nathanaelphilip** [comment]
fudge! ok, maybe it’s a package conflict. can you show me your package.json :)

**Comment by nathanaelphilip** [comment]
i think it may have to do with this package: https://github.com/visualfanatic/vue-svg-loader/issues/14
