### ISSUE TITLE
In production build CSS Sourcemaps in codesplit chunks are "duplicated", contained in both the .map file and the .js file

### ISSUE THREAD

**Issue by jakub300** [vuejs-templates/webpack#1110]
Steps to reproduce:
1. Generate project with vue-router, my exact answers:
```
? Generate project in current directory? Yes
? Project name vue-app
? Project description A Vue.js project
? Author Jakub Bogucki <jakub.bogucki@xfive.co>
? Vue build runtime
? Install vue-router? Yes
? Use ESLint to lint your code? No
? Setup unit tests No
? Setup e2e tests with Nightwatch? No
```
2. Install dependencies
3. edit `src/routes/index.js`:
    1. remove `import HelloWorld from '@/components/HelloWorld'`
    2. replace `component: HelloWorld` with `component: () => import('@/components/HelloWorld')`
4. build project for production
5. open `dist/static/js/0.[hash].js`
6. format it so you can see it well :)
7. somewhere in the file you should see something like that:
![image](https://user-images.githubusercontent.com/610941/33219097-cb8caf2a-d140-11e7-9bf2-0c9780ac88a6.png)

**Comment by LinusBorg** [comment]
Thanks for posting this. I have a few questions:

1. What CSS is duplicated? CSS from code-split .vue files is *not* added to the main app.css file that gets extracted - at least that's how it's supposed to work. Are you sure it's duplicated?
2. The production build generates sourcemaps. I'm not sure weither they should be included in the code-split bundle (to put it another way: if webpack simply behaves this way with sourcemaps for codesplit bundles), and if not, we can do anything about this from within this template (read: this would probably have to be fixed in vue-loader

I'll take as soon as I find some time to really dig into this.

**Comment by LinusBorg** [comment]
Okay, so I've taken a look. 

### My observations

1. CSS is not "duplicated" - css in a codesplit component only lives in the component, not in the main `app.css` file.
2. Sourcemaps are also not "duplicated" - the codesplit bundle contains the CSS Sourcemap for that codesplit bundle, while the `app.css.map` doesn't.
3. But including the sourcemap in that bundle is bad for file-size, so we should get it out of there somehow.
4. And finally: this also happens for "normal" `.js` files that are codesplit and import a normal `.css` file - in other words: webpack / style-loader does this, not Vue or vue-loader.

### Possible short-term fixes:

* disabling sourcemaps for production in `/config/index.js`.
* Setting `allChunks: true` in ExtractCSS extracts *all* css into `app.css`, even the CSS in codesplit bundles - this also extracts the sourcemap. But that might also be undesirable because I think by default, we *do* want the CSS to be in the codesplit bundle, but ideally, want the *sourcemap* for the CSS to be in a separate file.

## the end goal:

* Keep the CSS in the codesplit chunk
* Get the source-map out of the codesplit chunk

..however, I have no idea if that's actually possible with the current webpack tools we have.

Will investigate further.

**Comment by LinusBorg** [comment]
@vuejs-templates/collaborators take a look if you can.

**Comment by CharlesKumar** [comment]
In config/index.js 

look into

`...
build: {
  ...
  devtool: '#source-map'
  ...
}`

change this devtool value to configure bundle to whether to include sourcemaps or how to include them 

see the [docs](https://webpack.js.org/configuration/devtool/#production)

**Comment by LinusBorg** [comment]
@CharlesKumar Yes, this option allows to select a sourcemap, and we can also disable it there.

But that's not the problem we are dicussing.

**Comment by UncleBill** [comment]
>disabling sourcemaps in production is not a real solution to the problem we are discussing

Agree. We should split the sourcemap into isolation files, only leave the sourcemap file URL. That will save a lot bits.

**Comment by chrisvfritz** [comment]
@LinusBorg Could [extract-css-chunks-webpack-plugin](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin) provide a possible solution?

**Comment by LinusBorg** [comment]
@chrisvfritz not on its own. While it extracts css from code split chunks into individual css files (and with them possibly the sourcemaps), it leaves the chunk without runtime code to load that css. 

It seems to be meant in SSR scenarios specifically. 

I have hit up Sean on Twitter? hoping he has a pointer for us.

**Comment by CharlesKumar** [comment]
setting productionGzip: true may solve the problem

```
// Gzip off by default as many popular static hosts such as
    // Surge or Netlify already gzip all static assets for you.
    // Before setting to `true`, make sure to:
    // npm install --save-dev compression-webpack-plugin
    productionGzip: false,
```
a [thread](https://forum-archive.vuejs.org/topic/4059/adding-gzip-to-webpack-using-compression-plugin) from old vue forum

[[Just a [tip](https://varvy.com/pagespeed/enable-compression.html) to newbies who reading this comment]]

**Comment by LinusBorg** [comment]
Sorry, but that will only compress results, it won't remove the duplicated source maps

**Comment by CharlesKumar** [comment]
Agree that don't remove duplication

dead code elimination
disabling caching in production (not recommended)

uglifyjs [opions](https://github.com/mishoo/UglifyJS2#compress-options)

see toplevel, side_ffects, pure_getters('strict) for enhancement options 

The chunk may be marked as pure by webpack

[[minchunks: ... vs async: true in commonChunksPlugin]]

**Comment by jakub300** [comment]
Thanks for quick reaction to issues. By "duplicated" I meant that you can see it twice in the js file (for example in the screenshot) not that it's included in both js and css file. Sorry for not being clear enough.

**Comment by LinusBorg** [comment]
Well it's not really duplicated. One is the "real" css, one is the source css for the source map.

**Comment by LinusBorg** [comment]
After some discusssion with @chrisvfritz I think we should switch to `allChunks: true`.

**Comment by CharlesKumar** [comment]
I have a question to me but anyone here as webpack expert can solve

why aren't we harnessing [manifest.json](https://survivejs.com/webpack/optimizing/separating-manifest/)

> So now you have a little bit of insight about how webpack works behind the scenes. "But, how does this affect me?", you might ask. The simple answer is that most of the time it doesn't. The runtime will do its thing, utilizing the manifest, and everything will appear to just magically work once your application hits the browser. However, if you decide to improve your projects performance by utilizing browser caching, this process will all of a sudden become an important thing to understand.

Are we [bundle splitting](https://survivejs.com/webpack/building/bundle-splitting/) code to seperate the vendors or it is internally handled by commonschunks with hashids

**Comment by LinusBorg** [comment]
This has nothing to do with the problem at hand, please don't abuse issues for personal questions of interest.

**Comment by mfs780** [comment]
Just wondering if this issue is still present when setting allChunks to false.

**Comment by CodeLeom** [comment]
The fix for this issue is to create or edit your vue.config.js file 

With 


modules.export = { productionSourceMap : false }


Npm run build and all that's the fix
