### ISSUE TITLE
Vue.js working Fine in Chrome but not in IE 11

### ISSUE THREAD

**Issue by jaisrid81** [vuejs-templates/webpack#1142]
I have written all the logic inside an HTML Page. I am able to execute a piece of logic in Chrome, but in IE11 it says vue is undefined(when seen in developer options). Please find the file Attached

**Comment by jaisrid81** [comment]
[sample.txt](https://github.com/vuejs-templates/webpack/files/1528181/sample.txt)

**Comment by LinusBorg** [comment]
Hello @jaisrid81 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.

**Comment by jaisrid81** [comment]
Thanks @LinusBorg  : I have opened a thread in the forum "Code Working in Chrome but not in IE, gives vue.js as undefined". Please see the attached code there and help
