### ISSUE TITLE
Replace phantomjs/selenium with electron for testing?

### ISSUE THREAD

**Issue by fritx** [vuejs-templates/webpack#128]
> Under the covers it uses Electron, which is similar to PhantomJS but faster and more modern.
> \- nightmare

Here is part of what the change might look like:
- https://github.com/fritx/vuer/commit/9ca832beeea1cdd3b6ddafdec3ab50b7e45d4f5b
- https://github.com/fritx/vuer/commit/5d68bf39454b0a164bb82914b36e1c6d74733170

Pros:
- "Faster and more modern" & under more active development  (than phantomjs)
- No Java environment required (by selenium)

Cons:
- Mind the electron mirror https://github.com/electron/electron#mirrors

Related:
- https://github.com/segmentio/nightmare/issues/200
- https://github.com/electron/electron/issues/228

---

Oops. Just found that selenium part contains both chrome and firefox,
which can't be achieved by electron :sweat:

**Comment by chrisvfritz** [comment]
Very interesting! I'd never considered this use case for electron. It certainly does seem to have its benefits.

While I do feel some hesitation to switch from _the devil I know_, I think it might be worth the loss of Chrome + Firefox testing. I'm always developing in Chrome already and I can't remember the last time a test failed only in Firefox, honestly. The quirks usually result in things I'm _not_ testing for, like the alignment of an SVG node. I'd be curious to hear others' experiences.

The __speed__ of tests on the other hand, is a pain I definitely have felt on large applications. 🙂 If I could cut those build times down by half or a third, that'd be... amazing!

**Comment by yyx990803** [comment]
Selenium is still absolutely necessary, because Electron is only Chromium and we want to run tests in multiple environments. The default runs in Chrome & Firefox but the user can configure it to run in even more browsers.

The phantomjs usage is mostly for headless testing on CI environments. There are two concerns though: 

1. Electron's download size seems to be even heavier. (Phantom 17mb vs Electron 30~40mb)
2. Electron is not a pure-browser environment, with Node and it's own special globals. This may cause unexpected problems for user code that are solely intended for browser environments.

**Comment by guidobouman** [comment]
So, what about [jsdom](https://github.com/tmpvar/jsdom) for unit testing?

**Comment by chrisvfritz** [comment]
@guidobouman jsdom [isn't a full browser implementation](https://github.com/tmpvar/jsdom#what-standards-does-jsdom-support-exactly), so is probably more likely to cause failures for features that do in fact work in real browsers.

**Comment by chrisvfritz** [comment]
It seems that this isn't the right time to move away from phantomjs, due to the concerns @yyx990803 mentioned. It could well be that electron's node environment doesn't really cause problems in practice, but we probably don't want Vue users to be the guinea pigs in this experiment. When there are more examples of large projects using electron to test against, we can revisit this. 😃
