### ISSUE TITLE
npm WARN invalid config loglevel="notice"

### ISSUE THREAD

**Issue by gtalarico** [vuejs-templates/webpack#1303]
I just built a brand new project, and when I run `npm run build` I get the error below.
Please feel free to close this if it's not the appropriate place to report- maybe it's caused by one of my packages?

`npm WARN invalid config loglevel="notice"`

npm: 5.6.0
vue-cli: 2.9.1

![image](https://user-images.githubusercontent.com/9513968/36283454-985b37a2-1272-11e8-8935-95ab5874daa4.png)

**Comment by afontcu** [comment]
Google says that "This bug seems to be caused by installing a dependency that depends on an old version of NPM". ([source](https://github.com/npm/npm/issues/16862#issuecomment-358112152)).

Running `npm config set loglevel warn` might solve the issue, which I think is not related to vue-cli or this template.

Hope it helps!

**Comment by gtalarico** [comment]
This does not affect running or build, and it's likely not related to template itself, so closing this for now.
