### ISSUE TITLE
AirBNB linter results in "Unable to resolve path to module" errors for Vue files

### ISSUE THREAD

**Issue by quentinneyraud** [vuejs-templates/webpack#144]
When i run 
![vue-error](https://cloud.githubusercontent.com/assets/9378568/15652231/07d1d04a-2685-11e6-9839-5d91a7c85dae.png)
and then 
```bash
cd test
npm install
npm run dev
```
I have the following issues
![vue-error2](https://cloud.githubusercontent.com/assets/9378568/15652299/88a464da-2685-11e6-97bc-10c834fd472b.png)

I think they come from f9f69e1eb44fcf487d2b20216982c4a744ecbe8a, i made the same before this commit without errors and it's happen when i select AirBNB linter.

> node 6.2.0
> npm 3.8.9
> Debian Jessie

**Comment by lazystone** [comment]
I get the same. Template with airbnb profile is broken :(

**Comment by chrisvfritz** [comment]
This seems like a bug in [airbnb/javascript](https://github.com/airbnb/javascript), since Webpack is indeed able to resolve the path to the module. What would be ideal solution for users of this linting config? A few ideas:

- Specifically disable that rule in `.eslintrc.js`
- Add `.vue` to those import statements, which may fix the problem
- File in issue in the linting config so they can work better with Webpack

**Comment by RXminuS** [comment]
+1 ... Not really understand your guide @chrisvfritz? I'm assuming you mean there's an error in 'airbnb-base' which the .eslintrc.js extends?

In that case has someone opened an issue, and if so can we reference it here?

**Comment by chrisvfritz** [comment]
I've just disabled the rule, since Webpack will already let you know if a module can't be resolved. a5008e6d608093bd02cb1eb33b3e4f82ee31eae4

**Comment by karanssj4** [comment]
I created a gist which resolves this
https://gist.github.com/karanssj4/7188528ab36fb4e78c8fc385510f3136
