### ISSUE TITLE
Images are embedded, assets not copied

### ISSUE THREAD

**Issue by thany** [vuejs-templates/webpack#159]
When I execute `npm run build` I end up with a humongous javascript file (for what it does anyway), and none of the static assets are being copied to the dist folder. The reasons:

1) It somehow magically converts every static asset used, to a data-URI, embeds it in javascript, and have a script embed that in the DOM. This is absolutely crushing your performance. Also, this magic code makes it hard to track down any problems.

2) Any other static assets that aren't picked up by this magic should be copied over, but arent. In webpack.base.conf.js, I'm seeing two loaders that appear to copy and hash files into approriate directies (`img` and `fonts`) but none of that happens. If I add a png file, it's completely ignored and never copied over.

This is also very different from running a dev-server, where even CSS is embedded in javascript - also  a problem sooner or later. It's best to keep dev and prod as close to each other as possible, to avoid confusion about their differences, and potential problems.

Anyhow, I'm not seeing the statics end up in `dist`, so that a problem already.

**Comment by yyx990803** [comment]
`file-loader` config inlines any images smaller than 10k bytes as data-URI: https://github.com/vuejs-templates/webpack/blob/dist/template/build/webpack.base.conf.js#L67

This is more efficient for an extra HTTP request for a tiny image.

**Comment by thany** [comment]
When I place a larger file in `src/assets`, it still doesn't get copied over to the dist package.

**Comment by yyx990803** [comment]
I cannot reproduce this. Note the file only gets copied if it is somehow referenced in your templates. If it still happens for you, please provide a reproduction repo.

As for CSS, they are auto-extracted into standalone files for production builds, I'm not sure what you mean by "a problem sooner or later".

**Comment by thany** [comment]
By "a problem sooner or later" I meant that the CSS on dev is embedded (enclosed in the DOM) which has a higher specificity than external CSS (the usual way - referencing files). This makes for a functional difference between the two environments, which may lead to error that occur only on dev and not in the dis package, or vice versa.

If I have to somehow reference an asset in a temple in order for it to get copied, then that's a flaw. The script cannot possibly know that I've done, if I have, and it might also be referenced outside of the templates. I suggest to simply copy over all the assets. It cannot hurt to copy too many files, but copying too few files is a potential problem for sure.

**Comment by yyx990803** [comment]
Embedded CSS is not inline and it has no specificity difference from external CSS. The only thing that may affect specificity in this case is occurence order.

The build system does know when you reference assets in templates (they are turned into require calls by html-loader). Same for urls in your CSS. In JavaScript you reference assets using require (causing it to be resolved by file-loader). It's in fact a good thing to not copy things that you never used, so again, unless you have a reproduction case showing it's not working properly, I don't know what your problem is.

I suggest you do some reading on Webpack and the documentation of this template. If you simply disagree with how it is set up, then just roll your own.

**Comment by chrisvfritz** [comment]
@thany A couple other items worth noting:

- Webpack will process files referenced from _anywhere_ in your build system, including not only templates, but your JavaScript and CSS as well.
- If you just want some files to be copied over, rather than handled by Webpack's file-loader, you can put them in the `static` folder. This is rarely the right solution, but an example where it's appropriate is a `CNAME` file that surge (the hosting provider) looks for to assign a custom domain.
