### ISSUE TITLE
Removed Hello.vue styles, saved, no "hot-unload"

### ISSUE THREAD

**Issue by jbruni** [vuejs-templates/webpack#17]
Fresh install. Playing with Hello.vue, under `npm run dev`.

I've added

```
<style>
h1 { color: red }
</style>
```

and saved the file. The style has been hot-loaded and applied. Great!

Then, I've undone the change (removed the `<style>` I've added), and saved again. No change in the browser...

I had to add an empty `<style></style>` and save the file to see the styles removed in the browser.

Then, I could finally remove the tag, since the "undo" was done.

**Comment by chrisvfritz** [comment]
@jbruni This sounds like a feature request for another project, rather than a bug in this one. I recommend closing and opening a new issue in one of these:

- [vue-loader](https://github.com/vuejs/vue-loader/issues)
- [vue-hot-reload-api](https://github.com/vuejs/vue-hot-reload-api) (which seems to have issues turned off - is that on purpose @yyx990803?)

@yyx990803 should have a better idea of where that belongs.

**Comment by yyx990803** [comment]
This should be a `vue-loader` issue. I think I closed `vue-hot-reload-api`'s issues due to spamming a while ago, but it's not related to CSS hot reloading anyway.
