### ISSUE TITLE
Why the index.html in directory dist still contains <app></app>?

### ISSUE THREAD

**Issue by ihaichao** [vuejs-templates/webpack#175]
I create a project using vue-cli and it create index.html in directory dist when i run `npm run build`.
But the index.html is like this:
<img width="597" alt="2016-06-26 4 18 31" src="https://cloud.githubusercontent.com/assets/8586268/16361181/bcc5cbe8-3bb9-11e6-97b5-660d4a5257e6.png">

I think the index.html should be like this:
<img width="832" alt="2016-06-26 4 21 01" src="https://cloud.githubusercontent.com/assets/8586268/16361193/0cf90e86-3bba-11e6-96a5-b1e33b37207c.png">

Am I wrong?
BTW, what's the manifest.js and vendor.js for?

**Comment by chrisvfritz** [comment]
What you are describing is prerendering, which is outside the scope of this build. You can however use [prerender-spa-plugin](github.com/chrisvfritz/prerender-spa-plugin) to add this functionality. It's been tested with Vue and works very well!

The `vendor.js` file is where we keep common dependencies that will not change very often, such as Vue. The `app.js` file is for your actual application code. Then the `manifest.js` file is required by Webpack so that they can correctly work together and bust caches properly.

**Comment by ihaichao** [comment]
I think prerender-spa-plugin is for spa prerendering, what I want is building correct production outcome, do you have any other suggestions?
Many thanks.

**Comment by chrisvfritz** [comment]
As a primary maintainer of both this template and that plugin, trust me - it's what you're looking for. 😉 This template produces a SPA and if you want the "correct production outcome" written to index.html, you have to prerender it.

**Comment by ihaichao** [comment]
I tried your suggestion and it works. 
Thanks again for you patient help.
