### ISSUE TITLE
fsevents error on ubuntu

### ISSUE THREAD

**Issue by GitYong** [vuejs-templates/webpack#21]
I'm running into a dependence installing issue on Ubuntu 14.04. 

```npm WARN optional dep failed, continuing fsevents@1.0.7 
Killed```

**Comment by chrisvfritz** [comment]
@GitYong `fsevents` is an API available only on OS X. Since it's an optional dependency for at least one of the included packages, the failure should not kill the install. Since I haven't experienced this issue on Ubuntu, I don't think it's a bug in this project, but rather an npm or system quirk. 

My recommendation would be to close this issue and open up [a question on Stack Overflow](http://stackoverflow.com/questions/ask?title=npm%20WARN%20optional%20dep%20failed%2C%20continuing%20fsevents%401.0.7%20Killed).

**Comment by yyx990803** [comment]
Thanks @chrisvfritz for the explanation :)
