### ISSUE TITLE
vm.$refs is empty on unit tests

### ISSUE THREAD

**Issue by matt-sanders** [vuejs-templates/webpack#221]
Hi guys
When running the tests it seems that the $refs attribute is empty. If I log it, it just shows an empty object. Aren't all components supposed to be accessible through the $refs attribute?

**Comment by blake-newman** [comment]
Please follow the [Vue.js issue template](https://github.com/vuejs/vue/edit/dev/issue_template.md). 

Briefly an issue should contain:
- Dependency versions
- Steps necessary to reproduce the issue you are running into.
- A JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with [this template](http://jsfiddle.net/5sH6A/) that already includes the latest version of Vue.

If no information is provided, this issue will be closed within 5 days. If the issue is closed please reopen when relevant information is provided.

Thanks.

**Comment by chrisvfritz** [comment]
@matt-sanders That is not how `$refs` work. See [the docs](http://vuejs.org/api/#v-ref).

**Comment by gezichenshan** [comment]
@matt-sanders  I think you may lost to add $mount()
`
let vm = new Vue(Reg1).$mount()
`
