### ISSUE TITLE
Using vue-router

### ISSUE THREAD

**Issue by karneaud** [vuejs-templates/webpack#234]
I'm trying to use the cue-router module to switch components thus I have the following.

main.js

```
import Vue from 'vue'
import Resource from 'vue-resource'
import Router from 'vue-router'
import App from './components/app'
import Intro from './components/intro'

Vue.use(Resource)
Vue.use(Router)

const route = new Router()

// Pointing routes to the components they should use
route.map({
  '/': {
    component: Intro,
    subRoutes: {
      'app': {
        component: App
      }
    }
  },
  '/app': {
    component: App
  }
})

// Any invalid route will redirect to home
route.redirect({
  '*': '/app'
})

route.start(Intro, '#section')
```

in my intro.vue file I have 

```
<template>
<div class="container">
<div class="row">
<div class="column">
<h2>Create your MIA</h2>
<p><img src="../../static/intro.gif"/></p>
<p><a v-on:click="go()" href="#!/app" class="button">Enter</a></p>
</div>
</div>
</div>
</template>
<script>
export default {
  methods: {
    go: function () {
      console.log(this.$router.go)
      this.$router.go({ path: '/app' })
    }
  }
}
</script>
```

I have in my index.html

```
<body>
    <main class="container center">
      <div id="logo"></div>
      <div id="section">
        <router-view></router-view>
      </div>
    </main>
  </body>
```

However when I click on the anchor link....the has changes cut not the DOM content. I'm not sure why though

**Comment by chrisvfritz** [comment]
Since this is neither a bug or a feature request, I recommend posting your question on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).

**Comment by maxmckenzie** [comment]
i'm pretty sure that this has been sorted out in the many months since, however i ran into this problem and hit this post. i've made a gist here of a set up with this template https://gist.github.com/maxmckenzie/6a35c578be703fdc66556b468a2b3237 Basically i did not like the idea of pulling all of the imports into the main.js the code here still uses the App.js to load in components. I've not tested it with multiple routes just with home, but hopefully it'll help
