### ISSUE TITLE
vue-router not work with express

### ISSUE THREAD

**Issue by dolphineor** [vuejs-templates/webpack#26]
@yyx990803 Hi, I'm getting started with `vue-webpack-boilerplate`. I try to integrate `vue-router` with this template, but I have some trouble in changing view via router. When I start the server, I must reload the page to specific page through browser instead of vue-router, it seems like router doesn't work. I tried to figure out, but it's useless. I've been confused about it for a few days. Could you give me some advice or solutions? Thanks in advance.

**Comment by chrisvfritz** [comment]
@dolphineor When you say, "it seems like the router doesn't work", what code specifically is not working? And instead of the expected behavior, what is happening instead? Literally nothing, an error in the JS console, or something else?

Adapting [the `vue-router` _Basic Usage_ docs](http://vuejs.github.io/vue-router/en/basic.html), below is a minimal setup that should work within this boilerplate. Once you have that set up, `v-link`, `this.$router.go`, etc should work within all your components.

## Minimal `vue-router` setup

### `src/index.html`

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Vue App</title>
  </head>
  <body>
    <div id="app">
      <!-- route outlet -->
      <router-view></router-view>
    </div>
    <!-- built files will be auto injected -->
  </body>
</html>
```

### `src/main.js`

``` js
import Vue from 'vue'
import VueRouter from 'vue-router'
import configureRoutes from './routes'

Vue.use(VueRouter)
const router = new VueRouter({
  history: true,
  saveScrollPosition: true
})
configureRoutes(router)

router.start(
  Vue.extend({}),
  '#app'
)
```

### `src/routes.js`

The below assumes the referenced Vue components exist in a `src/pages` directory, which I often use for top-level page components.

``` js
import NotFound from './pages/not-found'
import Home from './pages/home'
import About from './pages/about'

export default router => {
  router.map({
    '/': {
      component: Home
    },

    '/about': {
      component: About
    }

    '*': {
      component: NotFound
    }
  })
}
```

**Comment by dolphineor** [comment]
@chrisvfritz Thanks! it's my fault, I provide an error value for transition property in ``` <router-view></router-view> ```
Now, it works.

**Comment by chrisvfritz** [comment]
@dolphineor Awesome!
