### ISSUE TITLE
Can we link to the docs in the description?

### ISSUE THREAD

**Issue by crswll** [vuejs-templates/webpack#270]
Too many people aren't aware documentation exists. Can we add it to the end of the description like many other projects seem to? I know I always look there.

**Comment by chrisvfritz** [comment]
I think this is a great idea!

**Comment by chrisvfritz** [comment]
@zigomir I just added this to the `2.0` branch. Not sure which other branches might also need updates. I see that `1.0` is now ahead of `dist` - is it now deprecated? If so, should we update the default branch to `1.0`?

**Comment by zigomir** [comment]
@chrisvfritz not really sure what do you mean. Are you asking if `dist` is deprecated? In any case, I'm not sure, I don't really use or watch `webpack` template.

I only know we have some extra code in `vue-cli` just to check if `dist` branch exists and use it if it does. I think we should remove it since `vue-cli` supports branches. Sorry, I might be off topic.

**Comment by chrisvfritz** [comment]
Got it. I guess this is a discussion including @LinusBorg as well then, since I see the `1.0` branch has received some commits that the `dist` branch has not. My understanding is that the `dist` branch is currently the default for this template though. Is that correct @zigomir? I just want to make sure we're all on the same page. 😄  Once we are, it would probably also be a good time to delete any branches we don't want.

**Comment by zigomir** [comment]
@chrisvfritz yes, that is correct. `dist` branch will be used by `vue-cli` by default (https://github.com/vuejs/vue-cli/blob/master/bin/vue-init#L116).

**Comment by LinusBorg** [comment]
Honestly I wasn't sure weither to add the two PRs of mine into `dist`, so I targeted `1.0` instead. 

Once we switch to the 2.0-version as the default template, (which should be right around the corner, right?) we could merge `2.0` into `dist` and I think we can leave `1.0` as it is.

**Comment by chrisvfritz** [comment]
I think I'd prefer to just remove the `dist` branch, since the other templates don't have one. We should probably keep it in the CLI though, in case other templates are relying on the behavior.

**Comment by LinusBorg** [comment]
...which will mean that old vue-cli versions will error out, right?

**Comment by zigomir** [comment]
@LinusBorg are you sure? This means that old `vue-cli` versions have hardcoded `dist` branch lookup?

**Comment by LinusBorg** [comment]
Well you linked to the source yourself above...

**Comment by LinusBorg** [comment]
Oh.. Wait. If no dist it returns the template without a branch tag, which should download the defAult branch? 

Then we should be fine.

**Comment by zigomir** [comment]
Yes, and also `checkDistBranch` is only for official templates so there should be no problem if we remove it.

**Comment by chrisvfritz** [comment]
This should be done now.
