### ISSUE TITLE
Watch static?

### ISSUE THREAD

**Issue by italomaia** [vuejs-templates/webpack#313]
It would be very nice to have the default template watching the static folder, because, there are a few huge libraries, like semantic, that work very nicely outside assets, and need to trigger a reload every time it is re-compiled.

**Comment by chrisvfritz** [comment]
The static folder is for assets that don't change - you can instead compile to the assets folder and require the CSS file from there. I wouldn't recommend this workflow however. Everything will work better and more as you expect if you let Webpack handle everything, rather than running multiple simulataneous build systems.

**Comment by italomaia** [comment]
Semantic-ui produces an huge css file. Webpack seems to not handle it very well. That is the reason for this issue.
