### ISSUE TITLE
Bug: Vue-Router erroring when vue.js is loaded from <script> tag in the HTML

### ISSUE THREAD

**Issue by KrishnaPG** [vuejs-templates/webpack#319]
Adding Vue-router to this template is throwing error `Unknown custom element: <router-link>` and `Unknown custom element: <router-view>` when the vue.js loaded from `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.js"></script>` in the HTML page.

The `<router-view>` is not getting recognized properly.

![image](https://cloud.githubusercontent.com/assets/4610831/19376676/a378bc8c-91fd-11e6-86e5-e1ac7a1f2cc6.png)

To reproduce, comment out the `import vue` line in the `main.js` and add the ` <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.js"></script>` in your HTML page and add some routes.

**Comment by LinusBorg** [comment]
Please provide at least the full `index.html` (preferably as it looks in the `/dist` folder when you ran `npm run build`) and `main.js`

**Comment by KrishnaPG** [comment]
Here is the basic code to reproduce the problem. After creating a sample app based on this webpack template, overwrite the content with below:
**index.html**
````
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>vue-webpack</title>

  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.js">    </script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue-router/2.0.1/vue-router.min.js"></script>	
  </body>
</html>
````
**main.js**
````

//import Vue from 'vue'

import App from './App'
import Hello from './components/Hello'

Vue.use(VueRouter);
var router = new VueRouter({
	mode: 'history',
	saveScrollPosition: true,
	routes: [
		{ path: '/', component: Hello },
	]
});

/* eslint-disable no-new */
new Vue({
  el: '#app',
  render: h => h(App),
  router: router  
})
````
**App.vue**
````
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>
````
You should see error
````
[Vue warn]: Unknown custom element: <router-view> - did you register the component correctly?
````
Note that both `Vue-Router` and `Vue` are loaded from CDN. 

If instead of loading through `script` tag, if you load the `vue` through `import` in the `main.js` it will work fine (with `vue-router` still being loaded from CDN)

Note sure `two copies of vue...` reasoning is correct. Because, in both cases `vue-router` is loading from CDN. Not sure how loading the `vue` with `import` will make the `vue-router` from CDN not load the 2nd copy.

If `vue-router` needs a copy of vue internally, it will always need it, irrespective of if `vue` is being loaded from CDN or not. May be something else is going wrong (unless the `vue` npm version is coming packed with `vue-router` that is some how overwriting the `vue-router` from the CDN so as to not create 2 copies)

**Comment by LinusBorg** [comment]
I'm pretty sure my reasoning is correct. The same thing happens when someone decides to do:

`import Vue from 'vue/dist/vue'` 

because he wants to load the standalone build ([why is this  bad idea (read the warning at the end) ?](http://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build)) 

Further explanation: Vue-loader needs to import vue as well, to use the template compiler for turning templates into render functions. 

It will assume that Vue is imported like this: `import Vue from 'vue'`, and you, therefore, end up with 2 versions of Vue in the bundled result.

In your case, you end up  one version of Vue in the global namespace (from CDN), and one required by vue-loader. The router is added to the first one (used in `main.js`) while all your `.vue` components are referring to the second one (bundled with webpack).

So: Don't include Vue (and possibly neither the router) via CDN if you want to use vue-loader.

**Comment by LinusBorg** [comment]
Also, as a (very important) sidenote: this effect only happens in dev mode, where vue-loader requires 'vue' to be used in HMR:

https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L220

a production build or a dev build with HMR disabled would be fine. But who wants to develop without HMR? :D

**Comment by KrishnaPG** [comment]
Thanks - the dev vs production info is what was missing. As long as it works in production, its great. Thanks for the external tip. Will look into it. You have been helpful.
