### ISSUE TITLE
dev-tools is on in production

### ISSUE THREAD

**Issue by fei-shen-null** [vuejs-templates/webpack#387]
Set `Vue.config.devtools=false;` manually disabled it.
But based on the docs 

>  This option’s default value is true in development builds and false in production builds.

Any ideal what went wrong?

**Comment by fei-shen-null** [comment]
I turned off source map in prod, still no luck.

**Comment by LinusBorg** [comment]
Hello

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
