### ISSUE TITLE
How to extract specify package to a single file

### ISSUE THREAD

**Issue by erguotou520** [vuejs-templates/webpack#389]
Sometimes the thirdparty component is heavy like [ElementUI](http://element.eleme.io/#/en-US).
Here is the [demo](https://github.com/erguotou520/vue-element).
After build the project, `vendor.js` is much large(500bk+), so I want to pack it to a single file(like element.hash.js). I tried to change `webpack.prod.conf.js` and add a new `CommonsChunkPlugin`, but not works. So give me some suggestion please.

**Comment by LinusBorg** [comment]
Hello @erguotou520 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
