### ISSUE TITLE
Question: How to run e2e tests with vue-resource?

### ISSUE THREAD

**Issue by znck** [vuejs-templates/webpack#393]
How to mock backend API requests for testing env only?

**Comment by LinusBorg** [comment]
Hello @znck

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
