### ISSUE TITLE
Config file that is excluded from bundle

### ISSUE THREAD

**Issue by DomenicRoti** [vuejs-templates/webpack#404]
Is it possible to have a config file (with my apikeys/endpoints/etc) that I load into my vue app, but keep excluded from my bundle?

I'm looking for a way to have a config file that can be edited by my build server depending on whether it's building in our dev/stage/uat/production environment.

Thanks

**Comment by LinusBorg** [comment]
Hello @DomenicRoti 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
