### ISSUE TITLE
npm run build : assetsPublicPath

### ISSUE THREAD

**Issue by JuanKraut** [vuejs-templates/webpack#442]
I've found myself doing the following. 

`vue init webpack`

`npm i`

`npm run build`

So the `dist` folder is created with its 3 bundles and corresponding maps. 
Now when you open the `index.html` generated by the build does not show anything.
(I know it is not suggested to open it from the filesystem) 
But if I remove the `/` from the assetsPublicPath property on the `config/index.js`

... then `index.html` does show the content of the template!

**Comment by LinusBorg** [comment]
> Now when you open the index.html

By that you mean that you opened with directly in your browser without any HTTP server, right?

In that case, the behaviour is expected, and can't bve changed by this template. 

When opening HTML files from the file system, the browser requires relative paths to read included files like scripts and images propertly. `publicPath: '/'` sets results in absolute paths, though.

This is the default because

1. This template is not meant to be used directly from the file system, but server over HTTP (it even  tells you about it in the console during build).
2. absolute paths are nessessary for code splitting and async components to work properly, especially when vue-router is involved.
