### ISSUE TITLE
Express server copied over when build.

### ISSUE THREAD

**Issue by bshandley** [vuejs-templates/webpack#459]
Hey, sorry if this is kind of a dumb question, but I'm new to Node/express/webpack. What is the best way to include an express server when I build my project for production? I basically want my 'dist' folder to have a server.js file that I can run to serve my SPA. My first thought would be to have a separate project that I could just drop the dist code into, but this seems a bit tedious. Am I going about this the wrong way? Thanks for any help you can offer!!

**Comment by LinusBorg** [comment]
> I basically want my 'dist' folder to have a server.js file that I can run to serve my SPA.
> *[...]* My first thought would be to have a separate project that I could just drop the dist code into, but this seems a bit tedious. 

* If it's  an app that runs completely in the browser, then you don't need a server in your dist folder - just use static hosting like surge.sh
* If it uses some kind of backend server (for a database and stuff), then yes, it's better to roll this as a seperate project, because it will have its own requirements and can hardly be crammed into the frontend template.

**Comment by bshandley** [comment]
Great! Thanks for the quick feedback! I need to use Nodemailer to send a Contact Us email, so it sound like a separate app is the way to go. Thanks again!
