### ISSUE TITLE
Fail load static in Windows 10

### ISSUE THREAD

**Issue by totomakers** [vuejs-templates/webpack#476]
Hey,
+ Installing last vue-cli
+ Create a new project 
+ try to load a static css file (bootstrap)
    + Open index.html
     + Adding `<style src="/static/oneui/css/bootstrap.min.css" type="text/css"></style>`

According to the doc, "/static/*" path will not be process by Webpack.
It will search in `assetsPublicPath` + `assetsSubdirectory`, base configuration looking in '/static' folder of project.

It's look like doesn't work on Windows (i pretty sure is Windows issue) anyone have a tips ? ❤️

**Comment by igeligel** [comment]
Some mistakes you make.
You should include your css by using the ``<link>`` tag. Rather than using ``<style src="/static/oneui/css/bootstrap.min.css" type="text/css"></style>`` use:

```html
<link href="./static/oneui/css/bootstrap.min.css" rel="stylesheet" type="text/css">
```

The dot in the href will reference the current directory you are in. Since you will write this to the ``index.html`` i believe you are in the root directory of the project. Then navigate to your css file.

Read [this source](https://developer.mozilla.org/en/docs/Web/HTML/Element/link) on how the link tag is working.

**Comment by totomakers** [comment]
Oh I feel bad ! Thanks for your answer ! Im stupid !

Thanks again

Le 4 févr. 2017 11:56 PM, "Kevin Peters" <notifications@github.com> a
écrit :

**Comment by totomakers** [comment]
Just

**Comment by aron-bordin** [comment]
is it not possible to load static assets with the <style> tag ? why ? I'm facing the same problem that @totomakers on linux, but I don't see why I would need to use  the <link> tag instead.

**Comment by igeligel** [comment]
It is not possible to load any kind of asset into a ``<style>`` tag. Read through the documentation of the style-tag [here](https://developer.mozilla.org/en/docs/Web/HTML/Element/style).

The ``<style>``-Tag is just used for inline styling inside HTML. In Vue they are also used in this way (in the end your ``style``-tags will be translated into inline style tags of the html).

**Comment by aron-bordin** [comment]
https://vue-loader.vuejs.org/en/start/spec.html, the Src Imports shows how to load css files in the style tag. But I'm not able to use it in vue-webpack. It's working with relative path, but absolute paths does not work, as pointed by @totomakers
