### ISSUE TITLE
Production mode refresh causing 404

### ISSUE THREAD

**Issue by jakubsikora** [vuejs-templates/webpack#511]
I have a simple router setup

```
const router = new Router({
  mode: 'history',
  scrollBehavior: () => ({ y: 0 }),
  routes: [
    {
      path: '/',
      name: 'index',
      redirect: '/foo',
    },
    {
      path: '/foo',
      name: 'foo',
      component: Foo,
    },
  ],
});
```

In dev mode is all working fine. When i run `npm run build` and generate static files in the `dist` folder and then serv it let say using npm `http-server` everytime I refresh from e.g. `localhost:8080/foo` I'm getting 404. 
I noticed that issue when I was trying to config `gh-pages` which base url is `username.github.io/repo_name/`. 

Is there something I didn't setup properly?

**Comment by kazupon** [comment]
This issue is not webpack template.
I guess that this issue is server setting.

See the vie-router docs
https://router.vuejs.org/en/essentials/history-mode.html

**Comment by alziqziq** [comment]
why its not working for me? @kazupon

**Comment by JeremyGranger** [comment]
@jakubsikora Did you ever figure this out? I'm running into the same issue using V2 + Webpack2 + NginX...

**Comment by jakubsikora** [comment]
@JeremyGranger I moved it to my DO server and used pm2 + reverse proxy on nginx following https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04 and its working fine.

**Comment by JeremyGranger** [comment]
Got it, thanks so much! You helped solve a very frustrating problem. Cheers!

Warmest Regards,
*Jeremy Granger*
*Software Engineer, Data Ductus, Inc.*
*Alumni, B.S.C.S. ‘15*
e: jeremy.granger@colorado.edu
c: 571.247.1432

On October 18, 2017 at 2:19:16 AM, Sikora Jakub (notifications@github.com)
wrote:

@JeremyGranger <https://github.com/jeremygranger> I moved it to my DO
server and used pm2 + reverse proxy on nginx following
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04
and its working fine.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vuejs-templates/webpack/issues/511#issuecomment-337499015>,
or mute the thread

**Comment by HACHIMIam** [comment]
i have the same issue when i try to serve the index file with live-server

**Comment by Heunsig** [comment]
@kazupon Thanks you :)

**Comment by mickaelbaron** [comment]
Hi,

I had the same issue. I followed this link: https://gist.github.com/szarapka/05ba804dfd1c10ad47bf

Mickael

**Comment by luis-abeno** [comment]
@kazupon Thanks =)
