### ISSUE TITLE
Failed on "npm run dev"

### ISSUE THREAD

**Issue by pa1nt3r** [vuejs-templates/webpack#550]
This is my first time setting-up vue-cli. I followed the step below but failed at "npm run dev".
please find the error log as attachment.

my local,
node v6.10.0
git version 2.12.0.windows.1
npm 4.3.0

$ npm install -g vue-cli
$ vue init webpack myvue
$ cd  myvue
$ npm install
$ npm run dev

[2017-02-26T07_46_33_630Z-debug.zip](https://github.com/vuejs-templates/webpack/files/801782/2017-02-26T07_46_33_630Z-debug.zip)

**Comment by LinusBorg** [comment]
Are you runing anything else on Port 8080, by any chance?

**Comment by pa1nt3r** [comment]
No, there is nothing running on Port8080 and i have tried to use other port but get the same result.

**Comment by LinusBorg** [comment]
Sorry, no idea what that error means then. :(

**Comment by pa1nt3r** [comment]
FYR,
  I solved this issue by commented out the first line in build/dev-server.js file (_//require('./check-versions')()_) then it works fine. 

* the check-versions.js seems to return false value.

**Comment by joemanfoo** [comment]
So - here's the strangest.  One windows 10 machine works and another doesn't - all pointing to the same exact code.  It's literally the same exact code since its on a network drive.

@pa1nt3r  mentioned commenting out the require check-versions pointed me to something to look at/into and it seems as though on one machine it cannot run the "npm --version".

I believe the root of the problem is that I've a bad value in my path var and get "The system cannot find the path specified." which is making the:
    require('child_process').execSync('npm --version').toString().trim()
to throw an error.

I've ran through my PATH var manually and cannot find a reference in there that's bad so something somewhere else is failing.

Still searching for the culprit but in the meantime folks who are curious can safely comment out that line of code @pa1nt3r mentions above as long as you know you have the node and npm requirements met.

Hope this helps someone - know it's bugged the you know what out of me.

**Comment by mikeconstable** [comment]
This is an old thread, but if it helps anyone else, I fixed the failing "npm run dev" command by  changing the port to 3000 on line 26 in /config/index.js.
