### ISSUE TITLE
feature request: add service-worker support

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs-templates/webpack#647]
Hello!
it would be very helpfully if your template have another one ask when initiated "Service worker support (Y/n)?"

And if I set "Yes" some steps should be performed:
1. add serviceworker-webpack-plugin to package.json dependency
2. /test/unit/index.js should exclude src/sw.js
3. karma.conf.js should configure to allow register sw.js from test

is it possible ? thanks!

**Comment by LinusBorg** [comment]
Thanks for this suggestion.

However, we currently don't want to make the template heavier by adding more questions in the initial setup. Also, Service Workers would rather be a topic for a special "PWA" template.

We will overhaul this template soon anyway, hopefully in the coming weeks, so I will close this request for now. This feature should be added in another template.

**Comment by maoberlehner** [comment]
Hey @LinusBorg,

I know there is a separate PWA template https://github.com/vuejs-templates/pwa but I don't think this is the best way to handle this feature. Because, although the differences between this and the PWA template are / were very minor, the PWA template is constantly out of sync with this template, which is annoying. I considered to contribute my time to keep the PWA template in sync, but I don't think it would be the best use of my time, to be honest.

I'd like to work on a pull request which adds (opt-in!) PWA support to this template, similar to how `create-react-app` handles this in its upcoming release (https://github.com/facebook/create-react-app/pull/3817).

Would you consider accepting such a pull request, or should I work on the PWA template instead?

**Comment by LinusBorg** [comment]
Hi @maoberlehner,

Thanks for contributing. However I don't think that we should add PWA support to this template - primarily because vue-cli 3 will come with (opt-in) support for it anyway. 

So my general strategy for this template would be to not add any more bigger features, especially when they are covered by the new cli. 

I will make an exception for typescript support mainly because I wanted to merge the OR for this for about half a year and didn't get around to it...

**Comment by maoberlehner** [comment]
Thanks for your quick answer, didn't know about the big changes coming with vue-cli 3, I guess than It's fine :)

**Comment by FossPrime** [comment]
@maoberlehner  Some docs on how to retrofit it would be welcome... did you figure it out?

**Comment by maoberlehner** [comment]
@rayfoss no, I'm using Vue CLI for everything now.
