### ISSUE TITLE
Built files rely on an http server

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [vuejs-templates/webpack#694]
Currently the built files in `/dist` folder requires a local server to serve the content.

I did a bit of tinkering and realize that by adding a dot `.` in front of the `/static/...` and change them to `./static/...`, the `index.html` can now be served over `file://` instead of the http protocol. Also with limited testing, (with `python -m http.server`), the added `.` didn't affect the ability to serve over the http protocol either.

Looks we can save a number of key strokes to add that useful dot without impact the functions. But manually adding this would be counter-productive, so I would need some help to try to get webpack to do it. Any easy to follow learning material?

What would be even greater is to incorporate this dot into the scaffolding, so every project would have this.

thanks!

**Comment by LinusBorg** [comment]
Looking at #200, #530, 541 this is not as simple as it looks. It's ok for a simple app but needs thorough testing for apps using vue-router and/or lazy loading of code-split components.

Since local usage is not the focus of this template, we will rather keep settings in place that work well with those technologies, which we expect most devs will use when writing a biger app with this template.

Since this topic is already discussed in the other mentioned issues and PRs, I will close this as a duplicate.
