### ISSUE TITLE
Hot-reload works only on production environment

### ISSUE THREAD

**Issue by miquelangel-castillo** [vuejs-templates/webpack#70]
Hi everybody, 

I'm trying hot-reload with chrome and the only way to success is with the **production** flag enabled on my **.npmrc** file

I'm running the build command **npm run dev**

Thanks for all your great job!

**Comment by yyx990803** [comment]
Sounds weird. OS, Node, npm versions?

**Comment by miquelangel-castillo** [comment]
I'm working with:

OS: Ubuntu 14.04
Node: 5.9.1
npm: 3.6.0
vue-cli: 1.4.0

**Comment by chrisvfritz** [comment]
@miquelangel-castillo Changing values in `data` don't trigger a reload because those values are only the _initial_ state for the component. When a component has already been initialized, changing that initial state has no effect. One important difference between hot reloads and a refresh are that reloads maintain the current state of components.

If you add `method` or `computed` functions and change those, does the hot reloading work then?

**Comment by yyx990803** [comment]
I thought [this](https://github.com/vuejs-templates/webpack/blob/master/template/src/components/Hello.vue#L11-L14) was clear enough?

Also, in production you are seeing a **full reload**, not a hot reload. The hot reload preserves your current application state.

**Comment by miquelangel-castillo** [comment]
@chrisvfritz I tried with methods and computed properties and hot-reload works fine as expected :))

@yyx990803 thanks for the explanation, it has become very clear to me

Thanks so much and congratulations for this great project

**Comment by chrisvfritz** [comment]
@miquelangel-castillo Glad to hear it! And glad you're enjoying Vue. 😀

**Comment by andrewhu** [comment]
Updating node and npm also fixed my problem. The vue dev tools chrome extension rocks! thanks
