### ISSUE TITLE
Headless Chrome for unit tests

### ISSUE THREAD

**Issue by frandiox** [vuejs-templates/webpack#726]
Headless Chrome (v59): https://developers.google.com/web/updates/2017/04/headless-chrome
Support in `karma-chrome-launcher`: https://github.com/karma-runner/karma-chrome-launcher/pull/111
Chrome release calendar: https://www.chromium.org/developers/calendar
Windows progress (maybe v60?): https://bugs.chromium.org/p/chromium/issues/detail?id=686608

Hi! Looks like finally, we will be able to use a headless version of Chrome for unit testing. What do you think about using Chrome instead of PhantomJS (or as an extra option)?

I've replaced PhantomJS with this headless Chrome in my local environment ([like this](https://github.com/frandiox/vue-onsenui-webpack/commit/22e109960625f0b5d2535f418eb40a2c2d33a550)) and it works well for now. Web Components and other new APIs can be used in tests :)

**Comment by corbinu** [comment]
Agreed PhantomJS is no longer being developed

**Comment by LinusBorg** [comment]
We will definitely consider this. The question not if, just when.

**Comment by kazupon** [comment]
I checked at [my boilerplate](https://github.com/kazupon/vue-plugin-boilerplate/commit/d2ef3ad674c393802886219ed5cabc6ef8d1761f) too.

It's works! 🚀 

unit test:
<img width="961" alt="screen shot 2017-07-02 at 12 30 37 am" src="https://user-images.githubusercontent.com/72989/27763605-4c1aeb9a-5ec1-11e7-9ff2-8b9b5a380e18.png">

e2e with ngihtwatch:
<img width="493" alt="screen shot 2017-07-02 at 12 37 49 am" src="https://user-images.githubusercontent.com/72989/27763611-72f2c350-5ec1-11e7-8287-ad63b38b9aeb.png">

We should be used Chrome headless instead of PhantomJS. 😉

**Comment by myst729** [comment]
@kazupon The CI server doesn't even have a GUI, is Chrome headless available there?

**Comment by nickmessing** [comment]
@myst729, headless means "without GUI"

**Comment by frandiox** [comment]
@myst729 Just install Google Chrome from your CI recipe. CircleCI example [here](https://github.com/OnsenUI/OnsenUI/blob/master/circle.yml#L26) -- latest `google-chrome-stable` for Linux includes "headless" feature, not sure about other OS.

**Comment by myst729** [comment]
Great! Will definitely give it a try.

**Comment by nickmessing** [comment]
@frandiox, same for Mac OS, not for windows yet

**Comment by mul14** [comment]
When Chrome headless will be part of vuejs webpack template by default?

**Comment by LinusBorg** [comment]
We'll shortly be switching to Jest (#817) so Karma will only coexist as a "deprecated" alternative for a while.

**Comment by 38elements** [comment]
Puppeteer requires NodeJS@6.4.0+.
I think it is better to use [Puppeteer](https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer).
