### ISSUE TITLE
Run in file:// protocal

### ISSUE THREAD

**Issue by erguotou520** [vuejs-templates/webpack#90]
Currently, the `dist` folder can't run under `file://` protocal, but sometime we still need that like `cordova` project. So can you provide a webpack config for this scence?

**Comment by chrisvfritz** [comment]
@erguotou520 I believe this is a Cordova configuration issue, rather than a problem with the template. [Does this fix your problem](http://stackoverflow.com/questions/9073953/phonegap-on-ios-with-absolute-path-urls-for-assets)?

**Comment by erguotou520** [comment]
@chrisvfritz It's better to build sources to relative rather than absolute in Cordova project, so I can both run in browser and my phone.

**Comment by chrisvfritz** [comment]
@erguotou520 Just to give you an update, we're considering changing all the generated paths to relative rather than root-relative. Just exploring first whether there are any edge cases where this wouldn't work.

**Comment by chrisvfritz** [comment]
@erguotou520 So in a Cordova, can use of [the `base` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) solve your problem?

**Comment by erguotou520** [comment]
I have tried to add this script in `index.html`:
```html
<script>
    var $base = document.createElement('base');
    $base.href = location.href;
    document.head.insertBefore($base, document.querySelector('meta'))
  </script>
```
It works in dev environment, but after build and run on Android, the sources using `/static/xxx`(absolute path) got 404.

![Uploading image.png…]()

**Comment by chrisvfritz** [comment]
@erguotou520 What about if `location.href` is updated to `location.protocol + '//' + location.host`?

**Comment by erguotou520** [comment]
Not worked, even better.
![image](https://cloud.githubusercontent.com/assets/7945757/15061738/5cc3fe16-136b-11e6-81a0-23c45ca18d6f.png)

**Comment by chrisvfritz** [comment]
OK, turns out I didn't really understand how the base tag works. 😞  For one thing, it apparently doesn't work at all on absolute URLs. But I just tested a modified build script in package.json:

``` json
"build": "node build/build.js && sed -i .bak -e 's/href=\"\\//href=\"/g' dist/index.html && sed -i .bak -e 's/src=\"\\//src=\"/g' dist/index.html && rm dist/index.html.bak",
```

It just removes the starting slash from any absolute URLs in the generated index.html. And it seems to work in one of my apps that I just tested it with! If you're on Windows, I believe you'd want to make sure you're using Git Bash or some other POSIX compliant shell.

**Comment by erguotou520** [comment]
If the absolute `static` path is not in `index.html`? Maybe in `app.js`?

**Comment by chrisvfritz** [comment]
Well you can do regex substitution with sed no matter what the file is. There'd likely be other ways you'd want to address the problem though, depending on where the absolute URLs are coming from. I'd need more information. 😕

**Comment by erguotou520** [comment]
I know your solution, maybe it's really a compromise way currently.

**Comment by chrisvfritz** [comment]
I've looked into this a bit more and some are claiming there are SEO concerns when using relative rather than root-relative paths, so this is starting to look like a `wontfix`. _However_... for mobile development, you may be interesting in [weex](http://alibaba.github.io/weex/), which very much inspired by Vue and is being actively developed by Alibaba Group, which is one of the largest tech companies in China.

**Comment by erguotou520** [comment]
Yeah, but this project started before `weex` is opened... and not going on these days...

**Comment by yozman** [comment]
@erguotou520
u can do like this
https://github.com/sth-cool/000/commit/e1927fdd0d80183daa2ae65cf85128329da6c7c3
