### ISSUE TITLE
Hot reload not working in fresh install

### ISSUE THREAD

**Issue by jupegarnica** [vuejs-templates/webpack#910]
Hello

I'm having an issue where hot reload is not working in a fresh install.

The solution mention at this [issue](https://github.com/vuejs-templates/webpack/issues/878 ) is not working for me, my vue-cli version is 2.8.2.

Any ideas why this might be happening?

**Comment by robwierzbowski** [comment]
Updating vue-cli shouldn't have any effect on the project code -- it's just for templating. 

What OS is your project on? Is the project in a folder with any special settings that could interfere with operating system events (e.g., Dropbox folder)?

**Comment by geniass** [comment]
I had the same problem, except it somehow affected all my projects (fresh installs and existing).
I'm running Fedora 25 and node v6.11.2

I'm not sure what the actual problem was, but I managed to fix it. I'm a bit surprised this works:

1. Delete your node_modules/ directory. I also deleted my ~/.npm directory but I'm not sure if this is required
2. Install [yarn](https://yarnpkg.com/en/)
3. `yarn install`

And now it works. Reinstalling all dependencies with npm didn't work, so it must be doing something wrong...

**Comment by geniass** [comment]
Actually this issue has reappeared. The fix this time is mentioned in [another issue](https://github.com/vuejs-templates/webpack/issues/378#issuecomment-263466173).

Adding the following to the `webpack-dev-middleware` config solved the issue this time:
```javascript
watchOptions: {
  aggregateTimeout: 300,
  poll: 1000
}
```

**Comment by JoseOspina** [comment]
I changed `config/index.js` to `poll: 1000`, and that worked too

**Comment by toudidel** [comment]
[geniass's solution](https://github.com/vuejs-templates/webpack/issues/910#issuecomment-331641177) (with using yarn) works for me properly
