### ISSUE TITLE
run dev mode not support some webview

### ISSUE THREAD

**Issue by xieminghao** [vuejs-templates/webpack#968]
![233](https://user-images.githubusercontent.com/5023352/31421639-02fbaed6-ae7b-11e7-90c2-a2b2032c6e60.png)

this picture shows while I am running dev mode, and debugging on my app webview. because the webview is not supportting for es6, I've got the error msg: `Uncaught SyntaxError: Use of const in strict mode.`
for now I have change the `const` to `var`, any else way to resolve the problem?

**Comment by LinusBorg** [comment]
Hello @xieminghao 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.

----

That being said, your code *should* be transpiled to Es5 by babel-loder - it seems this doesn't work, at least for that file. I suggest investigating in this direction.

**Comment by LinusBorg** [comment]
Ooops, correction: This was a bug. Explanation here

https://github.com/vuejs-templates/webpack/issues/967

Alsready fixed now.
