### ISSUE TITLE
Difficulty using isotopes and masonry with Vue Webpack

### ISSUE THREAD

**Issue by cbmaiolo** [vuejs-templates/webpack#995]
I'm pretty new to Vue and and webpack and ran into an issue trying to use isotopes in my project that was built with this template. After installing and importing isotopes from [vueisotope](https://github.com/David-Desmaisons/Vue.Isotope) I got the error:

 `This dependency was not found: * masonry/masonry in ./node_modules/isotope-layout/js/layout-modes/masonry.js`

This is an issue that a number of masonry users have encountered (see [can't resolve masonry/masonry](https://github.com/metafizzy/isotope/issues/1129) and [missing masonry module](https://github.com/David-Desmaisons/Vue.Isotope/issues/26)) and there is a recommended fix for it (see [metafizzy](https://isotope.metafizzy.co/extras.html#webpack)). The only problem is I am very ignorant and I either can't seem to get the fix to work, or don't know where to put it in this project. The recommended fix involves making changes to webpack.config.js and running webpack, but since I build this project with npm and webpack.config.js is no where to be found I've tried adding the line to /config/index.js with no success. I had difficulty determining if I should post this issue to the isotopes author, vueisotopes author or you, so I apologize if this is not in the right place, but it seems to be a resolvable issue for other people who have a webpack.config.js file, so this seemed like the best place.

**Comment by LinusBorg** [comment]
> but since I build this project with npm and webpack.config.js is no where to be found

The webpack config for this template is a bit more complicated than those you encounter in examples, because we cover a lot of features. For this reason, it's spread across more than one file, and those files live in the `/build` directory.

The file you want to edit is named `webpack.base.conf.js`. In this file, you will find the `resolve: alias` section that the website is describing. Simply add the described aliased there.

**Comment by cbmaiolo** [comment]
Thanks so much!
