### ISSUE TITLE
/* webpackChunkName: "name" */ is working without the exact name. 

### ISSUE THREAD

**Issue by SidKwok** [vuejs-templates/webpack#996]
My async route:
```javascript
const MainView = () => import(/* webpackChunkName: "group-foo" */ '@/components/MainView')
const OneView = () => import(/* webpackChunkName: "group-foo" */ '@/components/OneView')
const TwoView = () => import(/* webpackChunkName: "group-foo" */ '@/components/TwoView')
```

After I run build:
![1508482209806](https://user-images.githubusercontent.com/13268747/31808500-099d04aa-b539-11e7-8d26-3ac68672ccb1.jpg)

The bundle name is `0` rather than `group-foo`.

**Comment by LinusBorg** [comment]
Hm, that generally happens when comments are stripped, usually but babel. 

We had a `"comments: false"` setting in `.babelrc` for a long time(before webpack introduced this feature) which stripped comments from transpiled code and consequently broke this webpack feature.

But I removed this from the template back in June (https://github.com/vuejs-templates/webpack/commit/8563cdb8d8d1e4abaef64f7695697b70957b9490), so that *shouild* work. Could you verify that your `.babelrc` does not contain this setting?

**Comment by SidKwok** [comment]
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}
```

The `.babelrc` seems fine. And if `comments: false` setting in `.babelrc`, the magic comments are not supposed to work. I send a [PR](https://github.com/vuejs-templates/webpack/pull/997) and it should solve this issue.

**Comment by LinusBorg** [comment]
Thanks for the PR, will merge it as soon as I found time to take it for a quick spin.

**Comment by c0defre4k** [comment]
Hi, I don't see this as a bug. In production this shouldn't matter because the chunk is named properly as you can see in the Chunk names column. Only the file is named numeric.

Please also note that using name instead of id generates bigger manifest since the mapping for name to id has to be stored somewhere. See [here](https://webpack.js.org/configuration/output/#output-chunkfilename)

In this case I'd like to undo this change.

**Comment by SidKwok** [comment]
I see, it does have some side effects with `[name]`. And I agree that it shouldn't matter what the chunk name is in production, if the chunks are group together properly.

I think it's better to undo this change. @LinusBorg
